Addition docs adhering PEP257 and PEP8
mistralai/mistral-inference pull request #11
Opened 2023-09-28 11:02 UTC by rajveer43

Fixes #10

2023-09-28 14:48 UTC, timlacroix commented
Thanks for the docs ! @alexandresablayrolles will review some time next week.

2023-09-30 00:25 UTC, Sabersaber86 commented
From 372ba00898c400648c11202bbe3d5a962c207aa8 Mon Sep 17 00:00:00 2001
From: rajveer43 <rajveer.rathod1301@gmail.com>
Date: Thu, 28 Sep 2023 16:31:01 +0530
Subject: [PATCH] Addition of docs

---
 main.py              |  82 ++++++++++++++++++++++++++++++++-
 mistral/cache.py     |  92 +++++++++++++++++++++++++++++++++++--
 mistral/model.py     | 106 +++++++++++++++++++++++++++++++++++++++++++
 mistral/rope.py      |  22 +++++++++
 mistral/tokenizer.py |  22 +++++++++
 one_file_ref.py      |  63 +++++++++++++++++++++++++
 6 files changed, 382 insertions(+), 5 deletions(-)

diff --git a/main.py b/main.py
index 93cd506..3bc4c07 100644
--- a/main.py
+++ b/main.py
@@ -9,6 +9,19 @@
 
 
 def sample_top_p(probs: torch.Tensor, p: float):
+    """
+    Sample from the top-p distribution of probabilities.
+
+    Args:
+        probs (torch.Tensor): A tensor of probabilities.
+        p (float): The threshold for selecting tokens.
+
+    Returns:
+        torch.Tensor: The selected token(s).
+
+    Raises:
+        AssertionError: If p is not in the range [0, 1].
+    """
     assert 0 <= p <= 1
 
     probs_sort, probs_idx = torch.sort(probs, dim=-1, descending=True)
@@ -21,6 +34,22 @@ def sample_top_p(probs: torch.Tensor, p: float):
 
 
 def sample(logits: torch.Tensor, temperature: float, top_p: float):
+    """
+    Sample from the softmax distribution of logits with optional temperature and top-p filtering.
+
+    Args:
+        logits (torch.Tensor): A tensor of logits.
+        temperature (float): Temperature for controlling the sampling randomness.
+        top_p (float): The threshold for selecting tokens.
+
+    Returns:
+        torch.Tensor: The selected token(s).
+
+    Notes:
+        If temperature > 0, softmax sampling with temperature is applied.
+        If temperature = 0, greedy sampling is used.
+
+    """
     if temperature > 0:
         probs = torch.softmax(logits / temperature, dim=-1)
         next_token = sample_top_p(probs, top_p)
@@ -31,7 +60,32 @@ def sample(logits: torch.Tensor, temperature: float, top_p: float):
 
 
 @torch.inference_mode()
-def generate(prompts: List[str], model: Transformer, tokenizer: Tokenizer, *, max_tokens: int, chunk_size: int = None, temperature: float = 0.7):
+def generate(
+    prompts: List[str], 
+    model: Transformer, 
+    tokenizer: Tokenizer,
+    *, 
+    max_tokens: int,
+    chunk_size: int = None,
+    temperature: float = 0.7
+):
+    """
+    Generate text based on given prompts using a Transformer model.
+
+    Args:
+        prompts (List[str]): A list of text prompts.
+        model (Transformer): The Transformer model.
+        tokenizer (Tokenizer): The tokenizer for encoding and decoding text.
+        max_tokens (int): The maximum number of tokens to generate.
+        chunk_size (int, optional): The size of chunks for encoding prompts.
+        temperature (float, optional): The sampling temperature.
+
+    Returns:
+        Tuple[List[str], List[List[float]]]: A tuple containing:
+            - List[str]: Generated text based on prompts.
+            - List of List[float]: Log probabilities for each generated token.
+
+    """
     model = model.eval()
     B, V = len(prompts), model.args.vocab_size
 
@@ -41,7 +95,13 @@ def generate(prompts: List[str], model: Transformer, tokenizer: Tokenizer, *, ma
 
     # Cache
     cache_window = min(model.args.sliding_window, max(seqlens) + max_tokens)
-    cache = RotatingBufferCache(model.args.n_layers, model.args.max_batch_size, cache_window, model.args.n_kv_heads, model.args.head_dim)
+    cache = RotatingBufferCache(
+        model.args.n_layers, 
+        model.args.max_batch_size, 
+        cache_window, 
+        model.args.n_kv_heads, 
+        model.args.head_dim
+    )
     cache.to(device=model.device, dtype=model.dtype)
     cache.reset()
     
@@ -102,6 +162,15 @@ def generate(prompts: List[str], model: Transformer, tokenizer: Tokenizer, *, ma
 
 
 def interactive(model_path: str, max_tokens: int = 35, temperature: float = 0.7):
+    """
+    Interactively generate text based on user prompts using a Transformer model.
+
+    Args:
+        model_path (str): The path to the model directory.
+        max_tokens (int, optional): The maximum number of tokens to generate for each prompt.
+        temperature (float, optional): The sampling temperature.
+
+    """
     tokenizer = Tokenizer(str(Path(model_path) / "tokenizer.model"))
     transformer = Transformer.from_folder(Path(model_path), max_batch_size=3)
 
@@ -112,6 +181,15 @@ def interactive(model_path: str, max_tokens: int = 35, temperature: float = 0.7)
         print("=====================")
 
 def demo(model_path: str, max_tokens: int = 35, temperature: float = 0):
+    """
+    Demonstrate text generation using a Transformer model with predefined prompts.
+
+    Args:
+        model_path (str): The path to the model directory.
+        max_tokens (int, optional): The maximum number of tokens to generate for each prompt.
+        temperature (float, optional): The sampling temperature.
+
+    """
     tokenizer = Tokenizer(str(Path(model_path) / "tokenizer.model"))
     transformer = Transformer.from_folder(Path(model_path), max_batch_size=3)
 
diff --git a/mistral/cache.py b/mistral/cache.py
index f1e40a6..efbaa48 100644
--- a/mistral/cache.py
+++ b/mistral/cache.py
@@ -28,12 +28,38 @@ class RotatingCacheInputMetadata:
     seqlens: List[int]
 
 
-def interleave_list(l1: List[torch.Tensor], l2: List[torch.Tensor]):
+def interleave_list(l1: List[torch.Tensor], l2: List[torch.Tensor]) -> List[torch.Tensor]:
+    """
+    Interleaves two lists of tensors element-wise.
+
+    Args:
+        l1 (List[torch.Tensor]): The first list of tensors.
+        l2 (List[torch.Tensor]): The second list of tensors.
+
+    Returns:
+        List[torch.Tensor]: A new list containing elements interleaved from l1 and l2.
+
+    Raises:
+        AssertionError: If the input lists l1 and l2 have different lengths.
+    """
     assert len(l1) == len(l2)
     return [v for pair in zip(l1, l2) for v in pair]
 
 
 def unrotate(cache: torch.Tensor, seqlen: int) -> torch.Tensor:
+    """
+    Unrotates a 3D tensor along the first dimension.
+
+    Args:
+        cache (torch.Tensor): A 3D tensor of shape (W, H, D).
+        seqlen (int): The desired length of the output tensor.
+
+    Returns:
+        torch.Tensor: A new tensor obtained by unrotating the input tensor along the first dimension.
+
+    Raises:
+        AssertionError: If the input tensor cache doesn't have three dimensions (W, H, D).
+    """
     assert cache.ndim == 3  # (W, H, D)
     position = seqlen % cache.shape[0]
     if seqlen < cache.shape[0]:
@@ -44,8 +70,27 @@ def unrotate(cache: torch.Tensor, seqlen: int) -> torch.Tensor:
         return torch.cat([cache[position:], cache[:position]], dim=0)
 
 
+
 class CacheView:
-    def __init__(self, cache_k: torch.Tensor, cache_v: torch.Tensor, metadata: RotatingCacheInputMetadata, kv_seqlens: torch.Tensor):
+    """
+    A class for managing a cache of keys and values with associated metadata.
+    """
+    def __init__(
+        self, 
+        cache_k: torch.Tensor, 
+        cache_v: torch.Tensor, 
+        metadata: RotatingCacheInputMetadata, 
+        kv_seqlens: torch.Tensor
+    ):
+        """
+        Initialize a CacheView instance.
+
+        Args:
+            cache_k (torch.Tensor): The cache for keys.
+            cache_v (torch.Tensor): The cache for values.
+            metadata (RotatingCacheInputMetadata): Metadata about the cache.
+            kv_seqlens (torch.Tensor): The sequence lengths for keys and values.
+        """
         self.cache_k = cache_k
         self.cache_v = cache_v
         self.kv_seqlens = kv_seqlens
@@ -54,6 +99,12 @@ def __init__(self, cache_k: torch.Tensor, cache_v: torch.Tensor, metadata: Rotat
     def update(self, xk: torch.Tensor, xv: torch.Tensor):
         """
         to_cache_mask masks the last [sliding_window] tokens in ea [...]

2023-09-30 00:27 UTC, Sabersaber86 requested changes
Submit the approval with the changes

2023-10-13 04:37 UTC, rajveer43 commented
@alexandresablayrolles please review this

2023-10-18 14:39 UTC, timlacroix commented on main.py
> +    Sample from the softmax distribution of logits with optional temperature and top-p filtering.
tempeatures / top-p aren't optional ?

2023-10-18 14:39 UTC, timlacroix commented on main.py
> +        chunk_size (int, optional): The size of chunks for encoding prompts.
should fix typing into Optional[int]

2023-10-18 14:47 UTC, timlacroix commented on mistral/cache.py
> +        List[torch.Tensor]: A new list containing elements interleaved from l1 and l2.
maybe clarify what interleaving means with an example ?

2026-06-16 15:29 UTC, juliendenize commented
Hi! We're archiving this repository as it's no longer actively maintained, and therefore this pull request is being closed.

2026-06-16 15:29 UTC, closed without merging